### ISSUE TITLE
Strings are limited to 255 characters

### ISSUE THREAD

**Issue by 0xTim** [vapor/postgresql-driver#18]
When creating fields of type `String`, the driver translates them to a `VARCHAR` field of length 255 instead of using the `text` type available in PostgreSQL. Is there any way to use this type or do you have to specify a large `int` when preparing the database?

**Comment by 0xTim** [comment]
Closing this as it can be achieved with a `.custom` field like so:

```swift
posts.custom("contents", type: "TEXT")
```

**Comment by treaves** [comment]
That seems more of a work-around.  There shouldn't be any constraints added in the driver level that preclude standard functionality.
