### ISSUE TITLE
Crash in Serializer

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/postgresql-driver#19]
[Crash reported](https://github.com/vapor/vapor/issues/716#issuecomment-276031826) when trying to work around the Swift compiler described here vapor/vapor#716 I don't know exactly the issue but wanted to document this so it can be addressed in the right repo.  @MartinW can you better describe the crash here since this is where it will need to be fixed

**Comment by MartinW** [comment]
@kdawgwilk Crash occurs on isNull check. 

`Packages/FluentPostgreSQL-1.0.4/Sources/FluentPostgreSQL/PostgreSQLSerializer.swift:107`

```        
if (dict["id"]?.isNull)! {
            dict.removeValue(forKey: "id")
        }
```
