### ISSUE TITLE
Date type for Schema.Creator

### ISSUE THREAD

**Issue by lucianboboc** [vapor/postgresql-driver#24]
I think it would be useful to have the PostgreSQL Date/Time Types (https://www.postgresql.org/docs/9.1/static/datatype-datetime.html) added to the Schema.Creator, similar to `datetime` from the MySQL driver.

```
public func datetime(
        _ name: String,
        optional: Bool = false,
        unique: Bool = false,
        default value: NodeRepresentable? = nil
        ) {
        self.custom(name, type: "DATETIME", optional: optional, unique: unique, default: value)
    }
```

**Comment by natebird** [comment]
With 2.0 beta release this is now supported.

Closing.
