### ISSUE TITLE
2.0.0 support?

### ISSUE THREAD

**Issue by treaves** [vapor/postgresql-driver#25]
I'm trying to test out 2.0alpha; I'm currently blocked with no 2.0.0 alpha release for postgresql-provider. Any idea when it will be added?

Thanks.

**Comment by natebird** [comment]
@treaves We've been waiting for the alpha development on Fluent and MySQL to calm down a bit. MySQL and PostgreSQL are fairly similar in implementation so we can reuse a lot of code. That said, I'd like to bring PostgreSQL up to 2.0.0 across the driver and provider sometime this week if I can.

If you want to speed up the process by submitting some pull requests that would be great!

**Comment by treaves** [comment]
Thanks for the response.

I'll look at what it would take to contribute tonight; as I'm new to Swift, there is a bit of a learning curve.  More with he package management piece than with the language. I need to figure out the correct way to work on one module that has dependencies on another module, when the package manager is complaining about dependency versions.  I can't image I'd need to fork everything..

**Comment by treaves** [comment]
Is there anything being used to track what is going on across Vapor from a functionality perspective?  If I wanted to contribute to this module, @natebird you mention Fluent & MySQL; but I see no way of knowing what the design is, what work is in-progress, what work remains to be done, and what the intent is. SO how would anyone have any idea what needed to be done here to make this equivalent ?

**Comment by 0xTim** [comment]
@treaves you can look at the Fluent code to look at what needs to be done to get it to work with Fluent 2.0. There shouldn't be any more releases to Fluent 1 apart from critical bugs. In terms of design, the best thing to do is checkout the [Vapor documentation](https://vapor.github.io/documentation/) for how things work together.

Be warned though that the alpha releases of Fluent 2 are changing daily (including major breaking changes) and don't always build. I wouldn't recommend using Vapor 2 for anything other than curiosity until the betas start coming out when things get a bit more stable

**Comment by tanner0101** [comment]
> but I see no way of knowing what the design is, what work is in-progress,

@treaves We're trying to close as many open issues and feature requests as possible in Vapor 2 and Fluent 2. Issues like like https://github.com/vapor/fluent/issues/125.
That said, http://vapor.team is definitely the best place to get updates on what is going on and give input.

**Comment by natebird** [comment]
You can track the progress on this issue here: https://github.com/vapor-community/postgresql-driver/pull/27
