### ISSUE TITLE
Compatibility with Fluent 9

### ISSUE THREAD

**Issue by codynhat** [vapor/postgresql-driver#4]
Postgres seems outdated compared to MySQL. APIs can be changed to work with Fluent 9 (possibly newer?), using Node instead of Fluent.Value, etc.

**Comment by tanner0101** [comment]
@Prince2k3 and some others expressed interest in updating this soon. We are mainly focusing on keeping MySQL up to date while Vapor is in beta. That's your best bet for now at least.

**Comment by codynhat** [comment]
Great. I will try to dive in and see what I can do to help. Sounds like MySQL is what to look to as a guide?

**Comment by tanner0101** [comment]
Yup. MySQL is updated and working with the latest Vapor and Fluent.

Also check this out: https://vapor.github.io/documentation/fluent/driver.html

**Comment by codynhat** [comment]
Awesome. Thanks!

**Comment by Prince2k3** [comment]
@codynhat a PR for Fluent 10 support and latest snapshot is in progress.

**Comment by natebird** [comment]
This is resolved in PR #7 which is now merged and tagged 1.0.
