### ISSUE TITLE
Add additional native database types

### ISSUE THREAD

**Issue by natebird** [vapor/postgresql-driver#9]
- `.timestamp` -> `TIMESTAMP`
- `.timestampz` -> `TIMESTAMPZ`
- `.date` -> `DATE`
- `.json` -> `JSONB`
- `.uuid` -> `UUID`

Any others we should consider?

**Comment by natebird** [comment]
I would like to build this out to be fairly robust. I'm not a database guru but here is what the Ruby postgres gem supports: https://github.com/ged/ruby-pg/blob/1f274f68c16f1af1c642db1b9d3d28aef169dc84/lib/pg/basic_type_mapping.rb#L152-L215

**Comment by tanner0101** [comment]
Closing in favor of the issue on `vapor/fluent`. This needs to be added there first.
